# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0003_auto_20181018_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='add_to_all_events',
            field=models.BooleanField(default=False),
        ),
    ]
