# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0005_remove_category_add_to_all_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(null=True, to='events.Category'),
        ),
    ]
