# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0007_auto_20181022_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(default=b'Online', max_length=50),
        ),
    ]
