# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0008_auto_20181023_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(max_length=50),
        ),
    ]
