# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0010_auto_20181024_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineEvent',
            fields=[
                ('event_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='events.Event')),
                ('url', models.URLField(max_length=300)),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='PhysicalEvent',
            fields=[
                ('event_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='events.Event')),
                ('location', models.CharField(max_length=150)),
            ],
            bases=('events.event',),
        )
    ]
