# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0014_auto_20181031_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalevent',
            name='location',
        ),
        migrations.AddField(
            model_name='physicalevent',
            name='location',
            field=models.ManyToManyField(to='events.Location'),
        ),
    ]
